### ISSUE TITLE
"bazel coverage" causes a link error on Linux.

### ISSUE THREAD

**Issue by yasushi-saito** [grailbio/bazel-toolchain#1]
The linker emits a bunch of warnings of form

bazel-out/k8-opt/bin/bio/encoding/_objs/encoding/bio/encoding/fastx_iter.o:fastx_iter.cc:function __llvm_gcov_init: error: undefined reference to 'llvm_gcov_\
init'    

 It looks like @bazel_tools/embedded_tools/tools/cpp/ unix_cc_configure.bzl, _coverage_feature hardcodes the flags for gcc. This function switches on whether or not the platform is darwin, but it's really clang vs gcc.

**Comment by siddharthab** [comment]
Yes, this toolchain is missing some flags for instrumentation. I left them out in the toolchain, because coverage generation for llvm right now does not quite work completely, even with the flags.

https://github.com/bazelbuild/bazel/issues/1118#issuecomment-387133237

I will add those flags in for both linux and darwin to remove the warnings.
