### ISSUE TITLE
LLVM tools package symlink broken if LLVM repo isn't first fetched

### ISSUE THREAD

**Issue by kmicklas** [grailbio/bazel-toolchain#125]
In order to work around https://github.com/bazelbuild/bazel/issues/7746, the `llvm` package which has tool binaries like `:bin/clang` creates a symlink to the LLVM repository:

https://github.com/grailbio/bazel-toolchain/blob/a912bb381b36437be0eeb22de11f0ea198450b4e/toolchain/internal/configure.bzl#L91

Neither this symlink nor anything else seems to get a dependency on the LLVM repo registered with Bazel. If you run `bazel clean --expunge` and `bazel run @llvm_toolchain//llvm:bin/clang`, it will fail.

`bazel fetch`ing the appropriate LLVM repo "fixes" this, but this isn't a solution because it requires non-standard setup commands, something use of Bazel shouldn't require.

**Comment by siddharthab** [comment]
Sorry for the inconvenience.

The recommended usage pattern was changed recently when the configuration and toolchain repos were separated. The recommended way to access the distributed tools is now `@llvm_toolchain_llvm//:bin/clang-format` (if you are using the default auto-generated LLVM distribution repo). The "Accessing Tools" [section](https://github.com/grailbio/bazel-toolchain#accessing-tools) in the README has also been updated to say this.

This will depend on the file directly without depending on the symlink. I will think of a way to explicitly break the targets following the old pattern so that people are not surprised when the repo cache is clean.

**Comment by kmicklas** [comment]
We're not using the auto-generated LLVM distribution repo, rather we're using custom `http_archive`s for each platform and `toolchain_roots` to bring them in.

As mentioned in the README, we can depend on the tools via the distribution repo, but as this varies by platform, we need a custom `select` layer. Since this project is already doing that essentially, it would be nice for this to be supported natively.

**Comment by jsharpe** [comment]
Along these lines if the toolchain is used in a `genrule` I get the following warning: `(11:51:49) WARNING: /home/ubuntu/.cache/bazel/_bazel_ubuntu/474acb7c2a8b439c8fdea333ac133359/external/org_openssl/BUILD.bazel:1685:8: input 'llvm' to @org_openssl//:asm is a directory; dependency checking of directories is unsound`

**Comment by siddharthab** [comment]
I thought a little bit more about this. The symlink is an undesired workaround, but is needed until the underlying bazel issue is fixed. The other solution is to generate an alias for the selected toolchain_root. But such a feature also does not exist in bazel.

Because you are using only http_archive based workspaces in toolchain_roots, I think a possible workaround is to have a repository rule that mimics http_archive but takes a dict of host-os-arch key to URLs. It is similar to the `llvm` repository rule in `//toolchain:rules.bzl`, but expects a full URL instead of the LLVM distribution name. This will also solve the use case of constantly trying to modify llvm_release_name.py to get the exact OS distributions the user wants to support.

**Comment by djmarcin** [comment]
> Along these lines if the toolchain is used in a `genrule` I get the following warning: `(11:51:49) WARNING: /home/ubuntu/.cache/bazel/_bazel_ubuntu/474acb7c2a8b439c8fdea333ac133359/external/org_openssl/BUILD.bazel:1685:8: input 'llvm' to @org_openssl//:asm is a directory; dependency checking of directories is unsound`

I am also getting this `unsound` warning. Did you discover a fix to this issue?

**Comment by siddharthab** [comment]
The solution is to not use the symlink directly; it's an internal-use only hack.

We made a couple of changes to how the LLVM toolchain repo can be defined. If you are bringing in multiple repositories to the toolchain_roots attribute, may I suggest you look at the other attributes available and see if they can satisfy your requirements. If yes, then the targets `@llvm_toolchain_llvm//:bin`, etc. will allow you to bring the tools, or libraries, etc. to your genrules. For some common tools, we have shortcuts available, like `@llvm_toolchain//:clang` (see README for other examples), that you can reference in your genrule.

**Comment by djmarcin** [comment]
We are not using the symlink directly, we pass `--extra_toolchains=@llvm_toolchain//:cc-toolchain-x86_64-linux` and our genrule uses `toolchains = ["@bazel_tools//tools/cpp:current_cc_toolchain"],` to set the `$(CC)` make variable. A reduced repro is here: https://github.com/djmarcin/bazel-toolchain-unsound-repro.

```
$ bazel build //:unsound
INFO: Analyzed target //:unsound (36 packages loaded, 1332 targets configured).
INFO: Found 1 target...
WARNING: /home/david/bazel-toolchain-unsound-repro/BUILD:1:8: input 'llvm' to //:unsound is a directory; dependency checking of directories is unsound
Target //:unsound up-to-date:
  bazel-bin/out
INFO: Elapsed time: 1.548s, Critical Path: 0.06s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
```

**Comment by siddharthab** [comment]
Ah thanks. Good to know about this use case. I will try to look into it some time.

**Comment by siddharthab** [comment]
I just pushed commit [de8386b](https://github.com/grailbio/bazel-toolchain/commit/de8386b818e771093e547fc782f2172f5f76140d) that will resolve your issue.

**Comment by djmarcin** [comment]
Thanks, that did resolve the warning, and it also appears to have resolved excessive build times on our remote exec cluster that we were seeing after updating llvm-toolchain! 🎉

**Comment by siddharthab** [comment]
Yes, I did not notice before that having the symlink to the directory was pulling in all the files from the LLVM release archive. I thought bazel would just pull the symlink without resolving it. We have very few C++ actions in our monorepo, so we did not notice the additional sandbox overhead. Anyway, thanks @jsharpe and @djmarcin both for reporting this.
