### ISSUE TITLE
Illegal absolute label syntax when using `toolchain_roots`

### ISSUE THREAD

**Issue by j2kun** [grailbio/bazel-toolchain#162]
Hi there,

I have a docker container I want to use `llvm_toolchain` with, and I have the docker container installing LLVM via

```
RUN wget -O llvm.sh https://apt.llvm.org/llvm.sh \
  && chmod +x llvm.sh \
  && ./llvm.sh 13
```

Running `dpkg -L llvm-13` shows the package is installed to `/usr/lib/llvm-13`. Then I added this to my workspace:

```
llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "13.0.0",
    toolchain_roots = {"": "/usr/lib/llvm-13"},
)
```

When I build the container and try `bazel build @llvm_toolchain//:all` I fails with

```
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':                                       
   Traceback (most recent call last):                                                                           
        File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 68, column 32, in llvm_config_impl
                llvm_repo_label = Label(toolchain_root + ":BUILD.bazel")  # Exact target does not matter.       
Error in Label: Illegal absolute label syntax: /usr/lib/llvm-13:BUILD.bazel
ERROR: Error fetching repository: Traceback (most recent call last):                                            
        File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 68, column 32, in llvm_config_impl
                llvm_repo_label = Label(toolchain_root + ":BUILD.bazel")  # Exact target does not matter.
Error in Label: Illegal absolute label syntax: /usr/lib/llvm-13:BUILD.bazel  
```

According to the bazel docs [it's OK to have a hyphen in the target name](https://bazel.build/concepts/labels#package-names).  So what's going on here?

**Comment by j2kun** [comment]
I'm afraid the documentation on what to do with docker isn't clear enough for me to understand. How do I point `llvm_toolchain` to use a pre-installed LLVM?

**Comment by j2kun** [comment]
FYI I am using `bazel-4.0.0-linux-x86_64` from https://github.com/bazelbuild/bazel/releases/download/4.0.0/bazel-4.0.0-linux-x86_64

**Comment by siddharthab** [comment]
Thanks for the report. This is most likely a bug in my code. Let me look into it more in detail soon. The fix could be very simple.

**Comment by siddharthab** [comment]
Let me know if your issue is not fixed. Thanks again for reporting.

**Comment by j2kun** [comment]
Now I get the following error:

```
ERROR: .../external/llvm_toolchain/BUILD.bazel:117:6: @llvm_toolchain//:clang-format: missing input file 'external/llvm_toolchain/bin/clang-format', owner: '@llvm_toolchain//:bin/clang-format'
ERROR: .../external/llvm_toolchain/BUILD.bazel:117:6 1 input file(s) do not exist
```

I have clang-format and friends sym-linked in `/bin/` and `/usr/bin/`. So I'm not exactly sure what it's looking for...

**Comment by siddharthab** [comment]
The toolchain assumes that certain tools and libraries are part of the distribution in the bin and lib subdirectories. So if your path is `/usr/lib/llvm-13` as in your original bug report, there must be a file called `/usr/lib/llvm-13/bin/clang-format`. You can see the full list we expect to be in [aliases.bzl](https://github.com/grailbio/bazel-toolchain/blob/c16d31a299f6d5b85f3699c679baf81ec1a48875/toolchain/aliases.bzl).

Can you let me know what you see when you run:
```
ls -l "$(bazel info execution_root)/external/llvm_toolchain/bin/clang-format"
```

**Comment by j2kun** [comment]
So `clang-format` is not part of a standard LLVM installation, but it seems that `apt install`ing it resulted in being found by bazel_toolchain anyway, because I'm running into a different error now. (If not, at worst I could sym link it)

Now it seems that setting `toolchain_roots` results in `no such package '@llvm_toolchain_llvm//': The repository '@llvm_toolchain_llvm' could not be resolved`

If I unset the `toolchain_roots` in `WORKSPACE` then it is able to find this definition (and proceeds to build LLVM from source).

As a reproducing example, see [this repository](https://github.com/google/fully-homomorphic-encryption/) on branch `docker-llvm` at commit https://github.com/google/fully-homomorphic-encryption/commit/7e04349e34b8fbbb769c805a5b99311a6d3cef29

Running `docker build -t fhe -f docker/ubuntu-jammy.Dockerfile .`  produces

```
ERROR: /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_google_xls/xls/ir/BUILD:772:8: 
no such package '@llvm_toolchain_llvm//': The repository '@llvm_toolchain_llvm' could not be resolved: 
Repository '@llvm_toolchain_llvm' is not defined and referenced by '@com_google_xls//xls/ir:op_header'
```

**Comment by siddharthab** [comment]
There is an assumption in the line at https://github.com/google/xls/blob/a58a339fbfdbc9236b976b342a5523a16eeada63/xls/ir/BUILD#L775 that this project is being used without toolchain_roots. The repository `llvm_toolchain_llvm` will be defined only if the distribution URL is auto detected or if the `urls` attribute is used, i.e. no `toolchain_roots`.

If you are able to replace that line to be `@llvm_toolchain//:clang-format` instead of `@llvm_toolchain_llvm//:bin/clang-format`, you will be able to get past your error. The suggested replacement is a guaranteed alternative (and hence my comment above about requirement clang-format to always be present). There might be a few other places in your dependencies where you might face this problem, and you will have to make the same replacement everywhere. But there is another way (see last part of this note).

As for the comment about clang-format not being part of the standard LLVM install. We actually depend on the LLVM distribution as released on the LLVM website or the LLVM github repo. Installations through package managers are not guaranteed to work because different package managers have different assumptions on what will make their package complete. The install script you are using in your Docker build file has an option `all` to install a more complete set, otherwise it makes assumptions as well. In your docker image build, if you are willing to download and extract the relevant standard URL yourself and set the local path as the toolchain_root, you will get better mileage. You can extract it to `/` or `/usr` to make it look more like a package manager install.

If you extract the distribution yourself to a separate directory, you would also have a more efficient option of defining an external bazel workspace and then naming it `llvm_toolchain_llvm`. This way, you will not have to change your dependencies which depend on the presence of a workspace with that name containing the files from an LLVM distribution.

**Comment by j2kun** [comment]
Thank you for the help! I will look into these options.

**Comment by j2kun** [comment]
I'm trying to use the `urls` attribute now (no `toolchain_roots`), and that's failing because it can't find `@llvm_toolchain_llvm//:bin/llvm-cov`

```
DEBUG: Rule 'llvm_toolchain_llvm' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = {"debian-11-x86_64": "61582215dafafb7b576ea30cc136be92c877ba1f1c31ddbbd372d6d65622fef5"}
DEBUG: Repository llvm_toolchain_llvm instantiated at:
  /usr/src/fhe/WORKSPACE:77:15: in <toplevel>
  /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/rules.bzl:272:13: in llvm_toolchain
Repository rule llvm defined at:
  /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/rules.bzl:252:23: in <toplevel>
ERROR: /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/llvm_toolchain/BUILD.bazel:46:6: no such target '@llvm_toolchain_llvm//:bin/llvm-cov': target 'bin/llvm-cov' not declared in package '' (did you mean 'bin/llvm-ar'?) defined by /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/llvm_toolchain_llvm/BUILD.bazel and referenced by '@llvm_toolchain//:llvm-cov'
ERROR: Analysis of target '@llvm_toolchain//:llvm-cov' failed; build aborted: Analysis failed
```

My setup is 

```
http_archive(
    name = "com_grail_bazel_toolchain",
    strip_prefix = "bazel-toolchain-0.7",
    urls = [
        "https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.7.zip",
    ],
)

load("@com_grail_bazel_toolchain//toolchain:deps.bzl", "bazel_toolchain_dependencies")
                                                        
bazel_toolchain_dependencies()
                                                        
load("@com_grail_bazel_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(                     
    name = "llvm_toolchain",
    llvm_version = "14.0.0",
    urls = {
        "ubuntu-22.04-x86_64": [
            "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz",
        ],
        "debian-11-x86_64": [     
            "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz",
        ],
    },
)
```

Trying the same with `urls` as below (as per the readme) also doesn't work.

```
    urls = {
        "": [
            "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz",
        ],
    },
```

**Comment by siddharthab** [comment]
Thank you! This is a separate bug - filed #167.

For your use case, you would also need a `strip_prefix` argument. Check the example in the test here.

https://github.com/grailbio/bazel-toolchain/blob/2f6e6adf93f4bf34d7bce7ad797f53c82d998ba8/tests/WORKSPACE#L33-L36
