### ISSUE TITLE
Track unix_cc_toolchain_config from bazel's tools/cpp

### ISSUE THREAD

**Issue by mattgodbolt** [grailbio/bazel-toolchain#23]
I may be missing something but other toolchains seem to support thin_lto or other forms of LTO (https://github.com/tensorflow/tensorflow/blob/1843f39c11e42751837c62acfb74e1fe697353ef/third_party/toolchains/clang6/CROSSTOOL.tpl#L402 for example) -- it would be lovely to support that here. Or perhaps I'm mistaken: can someone suggest how I might enable LTO/pgo in general?

**Comment by siddharthab** [comment]
In general, this project is now lagging behind https://source.bazel.build/bazel/+/master:tools/cpp/unix_cc_toolchain_config.bzl.

Maybe I should also try to just use that rule directly without copy pasting code from there.

I am going to repurpose this issue towards that.

**Comment by mattgodbolt** [comment]
Thanks @siddharthab !

**Comment by siddharthab** [comment]
ThinLTO has now made it to @bazel_tools//tools/cpp:unix_cc_toolchain_config.bzl in bazel 1.0. So we can now refactor our code to depend on the rule there for this as well as other features.

**Comment by Monnoroch** [comment]
The standard `@bazel_tools//tools/cpp:unix_cc_toolchain_config.bzl` also supports more platforms, such as ARM (Android). There's an LLVM distribution for armv7a, yet this toolchain doesn't support it purely because of the lack of config, which already exists in Bazel. Would be great to reuse the main config and get all that!
