### ISSUE TITLE
undeclared inclusion(s) for stdlib

### ISSUE THREAD

**Issue by rockwotj** [grailbio/bazel-toolchain#50]
Error message on bazel 3.1.0 macosx
```
 undeclared inclusion(s) in rule '//:libaco':
this rule is missing dependency declarations for the following files included by 'aco.c':  '/private/var/tmp/_bazel_rockwood/220a37e812aa346f6c09d820eb20adae/external/llvm_toolchain/lib64/clang/11.0.2/include/stdint.h'
'/private/var/tmp/_bazel_rockwood/220a37e812aa346f6c09d820eb20adae/external/llvm_toolchain/lib64/clang/11.0.2/include/limits.h'
```

Those files exist? I'm using `absolute_paths = True` is there a reason this is happening?

**Comment by siddharthab** [comment]
The error message you are getting is because something is missing in the declared builtin include paths. I think we need to add a `lib64` directory in addition to the `lib` directory in these two places:
https://github.com/grailbio/bazel-toolchain/blob/f2d0aeca399e70297414341d228c7be460b4d6a0/toolchain/cc_toolchain_config.bzl.tpl#L504
https://github.com/grailbio/bazel-toolchain/blob/f2d0aeca399e70297414341d228c7be460b4d6a0/toolchain/cc_toolchain_config.bzl.tpl#L514

This could be independent of whether you are using absolute paths or not.

If you are familiar with how to test changes to external repos, can you test it and see if it resolves your problems? I am afraid I am not able to reproduce your issue easily.

As an aside, do you find the absolute paths feature useful? It has been a while since the feature was originally introduced, and there have been improvements in bazel sandbox since, so I was thinking of removing the feature.

**Comment by rockwotj** [comment]
@siddharthab Thanks for the speedy reply! I actually only use the absolute paths because without it https://github.com/bazelbuild/rules_foreign_cc/ does not work (I think it runs stuff from a different directory so the paths are incorrect).

Let me add in those patches and test

**Comment by rockwotj** [comment]
@siddharthab your suggestion to add `lib64` worked! 🎊

**Comment by siddharthab** [comment]
Awesome! Can you send a PR?

**Comment by siddharthab** [comment]
I have pushed a new tag (0.5.6) which has this fix.
